#!/usr/bin/env python3
"""
Fix UEFI PE32+ binary generated by aarch64-elf-objcopy.

Problems with objcopy's PEI output:
  - Section VirtualAddress may be 0, less than SizeOfHeaders (EDK2 rejects this)
  - ELF R_AARCH64_RELATIVE not converted to PE base relocations
  - NumberOfRvaAndSizes may be wrong

This script:
  1. Shifts all section VAs so the first section VA >= SizeOfHeaders
  2. Updates ELF R_AARCH64_RELATIVE addends in the binary data to match shifted VAs
  3. Creates a .reloc section with converted R_AARCH64_RELATIVE entries
  4. Sets up PE32+ data directories correctly
"""

import struct
import os
import sys


def align_up(x, a):
    return (x + a - 1) // a * a


def get_elf_sections(elf_path):
    """Return list of ELF sections with name, addr, offset, size, flags."""
    with open(elf_path, 'rb') as f:
        data = f.read()
    if data[:4] != b'\x7fELF' or data[4] != 2:
        return None, None
    e_shoff = struct.unpack('<Q', data[0x28:0x30])[0]
    e_shentsize = struct.unpack('<H', data[0x3A:0x3C])[0]
    e_shnum = struct.unpack('<H', data[0x3C:0x3E])[0]
    e_shstrndx = struct.unpack('<H', data[0x3E:0x40])[0]

    shstrtab_off = e_shoff + e_shstrndx * e_shentsize
    shstrtab_addr = struct.unpack('<Q', data[shstrtab_off+0x18:shstrtab_off+0x20])[0]
    shstrtab_sz = struct.unpack('<Q', data[shstrtab_off+0x20:shstrtab_off+0x28])[0]
    strtab = data[shstrtab_addr:shstrtab_addr+shstrtab_sz]

    sections = []
    for i in range(e_shnum):
        sh_off = e_shoff + i * e_shentsize
        sh_name = struct.unpack('<I', data[sh_off:sh_off+4])[0]
        sh_type = struct.unpack('<I', data[sh_off+4:sh_off+8])[0]
        sh_flags = struct.unpack('<Q', data[sh_off+8:sh_off+16])[0]
        sh_addr = struct.unpack('<Q', data[sh_off+0x10:sh_off+0x18])[0]
        sh_offset = struct.unpack('<Q', data[sh_off+0x18:sh_off+0x20])[0]
        sh_size = struct.unpack('<Q', data[sh_off+0x20:sh_off+0x28])[0]
        name = strtab[sh_name:strtab.index(b'\x00', sh_name)].decode() if sh_name < shstrtab_sz else ''
        sections.append({'name': name, 'addr': sh_addr, 'offset': sh_offset,
                         'size': sh_size, 'type': sh_type, 'flags': sh_flags})
    return sections, data


def get_elf_rela_relocs(elf_path):
    """Return (elf_data, list of (r_offset, addend) tuples for R_AARCH64_RELATIVE)."""
    sections, data = get_elf_sections(elf_path)
    if sections is None:
        return [], None
    for sec in sections:
        if sec['name'] == '.rela.dyn' and sec['type'] == 4:  # SHT_RELA
            relocs = []
            for j in range(0, sec['size'], 24):
                r_offset = struct.unpack('<Q', data[sec['offset']+j:sec['offset']+j+8])[0]
                r_info = struct.unpack('<Q', data[sec['offset']+j+8:sec['offset']+j+16])[0]
                r_type = r_info & 0xFFFFFFFF
                if r_type == 0x403:  # R_AARCH64_RELATIVE
                    r_addend = struct.unpack('<Q', data[sec['offset']+j+16:sec['offset']+j+24])[0]
                    relocs.append((r_offset, r_addend))
            return relocs, data
    return [], data


def elf_va_to_elf_offset(elf_data, elf_sections, va):
    """Convert ELF virtual address to ELF file offset."""
    for sec in elf_sections:
        if sec['addr'] <= va < sec['addr'] + sec['size']:
            return sec['offset'] + (va - sec['addr'])
    return None


def pe_rva_to_pe_offset(pe_sections, rva):
    """Convert PE RVA to PE file offset."""
    for sec in pe_sections:
        if sec['vaddr'] <= rva < sec['vaddr'] + sec['vsize']:
            return sec['roff'] + (rva - sec['vaddr'])
    return None


def fix_pe(pe_path, elf_path):
    with open(pe_path, 'rb') as f:
        data = bytearray(f.read())

    e_lfanew = struct.unpack('<I', data[0x3C:0x40])[0]
    if bytes(data[e_lfanew:e_lfanew+4]) != b'PE\x00\x00':
        print(f"  Not a PE file")
        return False

    pe_sig = e_lfanew
    coff = pe_sig + 4
    opt = coff + 20

    magic = struct.unpack('<H', data[opt:opt+2])[0]
    if magic != 0x20B:
        print(f"  Expected PE32+ (magic 0x20B), got 0x{magic:04X}")
        return False

    # PE32+ offsets (all from UEFI/PECOFF spec)
    OFFS_SIZEOFCODE        = 4
    OFFS_SIZEOFINITDATA    = 8
    OFFS_SIZEOFUNINITDATA  = 12
    OFFS_ENTRYPOINT        = 16
    OFFS_BASEOFCODE        = 20
    OFFS_IMAGEBASE         = 24
    OFFS_SECTIONALIGNMENT  = 32
    OFFS_FILEALIGNMENT     = 36
    OFFS_SIZEOFIMAGE       = 56
    OFFS_SIZEOFHEADERS     = 60
    OFFS_CHECKSUM          = 64
    OFFS_SUBSYSTEM         = 68
    OFFS_DLLCHARACTERISTICS = 70
    OFFS_NUMBEROFRVAANDSIZES = 108
    OFFS_DATADIRECTORY     = 112

    file_align  = struct.unpack('<I', data[opt+OFFS_FILEALIGNMENT:opt+OFFS_FILEALIGNMENT+4])[0]
    sect_align  = struct.unpack('<I', data[opt+OFFS_SECTIONALIGNMENT:opt+OFFS_SECTIONALIGNMENT+4])[0]
    entry_rva   = struct.unpack('<I', data[opt+OFFS_ENTRYPOINT:opt+OFFS_ENTRYPOINT+4])[0]
    num_sects   = struct.unpack('<H', data[coff+2:coff+4])[0]
    opt_hdr_sz  = struct.unpack('<H', data[coff+16:coff+18])[0]
    soh         = struct.unpack('<I', data[opt+OFFS_SIZEOFHEADERS:opt+OFFS_SIZEOFHEADERS+4])[0]

    # Parse PE sections
    sections = []
    s = opt + opt_hdr_sz
    for i in range(num_sects):
        name = data[s:s+8].rstrip(b'\x00').decode('latin-1').strip()
        vsize = struct.unpack('<I', data[s+8:s+12])[0]
        vaddr = struct.unpack('<I', data[s+12:s+16])[0]
        rsize = struct.unpack('<I', data[s+16:s+20])[0]
        roff  = struct.unpack('<I', data[s+20:s+24])[0]
        sections.append({'name': name, 'vsize': vsize, 'vaddr': vaddr,
                         'rsize': rsize, 'roff': roff, 'hdr_off': s})
        s += 40

    # Remove stale .reloc sections from previous runs
    stale = [sec for sec in sections if sec['name'] == '.reloc']
    if stale:
        for rs in reversed(stale):
            idx = sections.index(rs)
            del data[rs['hdr_off']:rs['hdr_off']+40]
            sections.pop(idx)
        num_sects = len(sections)
        struct.pack_into('<H', data, coff+2, num_sects)
        # Re-read header offsets
        s = opt + opt_hdr_sz
        for i in range(num_sects):
            sections[i]['hdr_off'] = s
            s += 40

    min_va = min(s['vaddr'] for s in sections)
    # Compute VA shift needed
    va_shift = 0
    if min_va < soh:
        va_shift = align_up(soh - min_va, sect_align)

    # --- Compute max_end (for .reloc VA) BEFORE any changes ---
    max_end = max(s['vaddr'] + s['vsize'] for s in sections)

    # --- Load ELF relocations ---
    elf_relocs, elf_data = get_elf_rela_relocs(elf_path)
    elf_sections, _ = get_elf_sections(elf_path)

    # --- Step 1: Shift all section VAs ---
    if va_shift > 0:
        entry_rva += va_shift
        struct.pack_into('<I', data, opt+OFFS_ENTRYPOINT, entry_rva)
        soh_code = struct.unpack('<I', data[opt+OFFS_BASEOFCODE:opt+OFFS_BASEOFCODE+4])[0]
        struct.pack_into('<I', data, opt+OFFS_BASEOFCODE, soh_code + va_shift)

        for sec in sections:
            sec['vaddr'] += va_shift
            struct.pack_into('<I', data, sec['hdr_off']+12, sec['vaddr'])
        max_end += va_shift

        # --- Step 2: Update addends in binary data ---
        for r_offset, addend in elf_relocs:
            # Find the ELF file offset for this r_offset
            elf_off = elf_va_to_elf_offset(elf_data, elf_sections, r_offset)
            if elf_off is None:
                continue
            # Read the addend value from ELF binary
            val = struct.unpack('<Q', elf_data[elf_off:elf_off+8])[0]
            # The addend in ELF virtual address terms. In PE terms, it needs +va_shift.
            new_val = val + va_shift
            # Find PE file offset for this r_offset (which maps to PE RVA = r_offset + va_shift)
            pe_off = pe_rva_to_pe_offset(sections, r_offset + va_shift)
            if pe_off is not None and pe_off + 8 <= len(data):
                struct.pack_into('<Q', data, pe_off, new_val)

    # --- Compute header size and reloc data ---
    headers_end = opt + opt_hdr_sz + num_sects * 40
    headers_sz = align_up(headers_end, file_align)

    # Build .reloc data
    rvas = [r[0] + va_shift for r in elf_relocs]
    reloc_data = bytearray()
    if rvas:
        pages = {}
        for rva in rvas:
            page_rva = (rva // 0x1000) * 0x1000
            off = rva - page_rva
            entry = (0xA << 12) | off
            pages.setdefault(page_rva, []).append(entry)
        for page_rva in sorted(pages):
            entries = pages[page_rva]
            blk_sz = 8 + len(entries) * 2
            reloc_data += struct.pack('<II', page_rva, blk_sz)
            for e in entries:
                reloc_data += struct.pack('<H', e)

    reloc_sz = len(reloc_data)
    padded_reloc = align_up(reloc_sz, file_align)
    reloc_data += b'\x00' * (padded_reloc - reloc_sz)

    # --- Step 3: Insert .reloc section header ---
    last_sect_hdr = opt + opt_hdr_sz + num_sects * 40
    new_hdr = bytearray(40)
    new_hdr[0:8] = b'.reloc\x00\x00'
    struct.pack_into('<I', new_hdr, 12, 0)
    struct.pack_into('<I', new_hdr, 8, reloc_sz)
    struct.pack_into('<I', new_hdr, 16, padded_reloc)
    struct.pack_into('<I', new_hdr, 20, 0)
    struct.pack_into('<I', new_hdr, 36, 0x42000040)

    data[last_sect_hdr:last_sect_hdr] = new_hdr
    num_sects += 1
    struct.pack_into('<H', data, coff+2, num_sects)

    # Fix existing PointerToRawData (shifted by 40)
    s = opt + opt_hdr_sz
    for _ in range(num_sects - 1):
        roff = struct.unpack('<I', data[s+20:s+24])[0]
        if roff != 0:
            struct.pack_into('<I', data, s+20, roff + 40)
        s += 40

    # Append reloc data at end
    cur_size = len(data)
    raw_off = align_up(cur_size, file_align)
    data += b'\x00' * (raw_off - cur_size)
    reloc_file_off = len(data)
    data += reloc_data

    # Update .reloc section header
    new_va = align_up(max_end, sect_align)
    struct.pack_into('<I', data, last_sect_hdr + 12, new_va)
    struct.pack_into('<I', data, last_sect_hdr + 20, reloc_file_off)

    # --- Step 4: Fix COFF characteristics ---
    chars = struct.unpack('<H', data[coff+18:coff+20])[0]
    chars &= ~0x0001
    chars |= 0x0020
    struct.pack_into('<H', data, coff+18, chars)

    # --- Step 5: Fix PE32+ required fields (all at PE32+ offsets) ---
    img_sz = new_va + max(align_up(reloc_sz, sect_align), 0x1000)
    struct.pack_into('<I', data, opt+OFFS_SIZEOFIMAGE, img_sz)
    struct.pack_into('<I', data, opt+OFFS_SIZEOFHEADERS, headers_sz)
    struct.pack_into('<H', data, opt+OFFS_SUBSYSTEM, 0x000A)
    struct.pack_into('<H', data, opt+OFFS_DLLCHARACTERISTICS, 0x0100)

    # Fix code/data sizes
    code_sz = file_align
    init_sz = file_align
    uninit_sz = 0
    for sec in sections:
        if sec['name'] == '.text':
            code_sz = align_up(sec['rsize'], file_align)
        elif sec['name'] in ('.rodata', '.data', '.dynsym', '.dynstr', '.hash', '.dynamic', '/4'):
            init_sz += align_up(sec['rsize'], file_align)
        elif sec['name'] == '.bss':
            uninit_sz += sec['vsize']
    init_sz += padded_reloc
    struct.pack_into('<I', data, opt+OFFS_SIZEOFCODE, code_sz)
    struct.pack_into('<I', data, opt+OFFS_SIZEOFINITDATA, init_sz)
    struct.pack_into('<I', data, opt+OFFS_SIZEOFUNINITDATA, uninit_sz)

    # --- Step 6: Set up data directories ---
    dd_start = opt + OFFS_DATADIRECTORY
    dd_count = 16
    data[dd_start:dd_start + dd_count * 8] = b'\x00' * (dd_count * 8)
    struct.pack_into('<I', data, opt+OFFS_NUMBEROFRVAANDSIZES, dd_count)

    if reloc_sz > 0:
        struct.pack_into('<I', data, dd_start + 5 * 8, new_va)
        struct.pack_into('<I', data, dd_start + 5 * 8 + 4, reloc_sz)

    with open(pe_path, 'wb') as f:
        f.write(data)

    print(f"  Fixed PE32+: {num_sects - 1}→{num_sects} sections, "
          f"Subsys=0x0A, SizeOfImg=0x{img_sz:X}, Hdrs=0x{headers_sz:X}, "
          f"VA_shift=0x{va_shift:X}")
    if rvas:
        print(f"  Added .reloc: {len(rvas)} entries at RVA 0x{new_va:X}")
    return True


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    build_dir = os.path.join(project_dir, 'build')
    pe_path = os.path.join(build_dir, 'BOOTAA64.EFI')
    elf_path = os.path.join(build_dir, 'kernel.so')

    if not os.path.exists(pe_path) or not os.path.exists(elf_path):
        print("ERROR: build BOOTAA64.EFI or kernel.so not found")
        sys.exit(1)

    if fix_pe(pe_path, elf_path):
        print("  PE32+ fix applied")
    else:
        print("  FAILED")
        sys.exit(1)


if __name__ == '__main__':
    main()
